# Generated by Django 2.1.7 on 2019-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotaciones', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
