# Generated by Django 2.1.7 on 2019-06-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Dataset')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unique', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TagBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=7)),
                ('x_top_left', models.FloatField(blank=True)),
                ('y_top_left', models.FloatField(blank=True)),
                ('width', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_by', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Experiment')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('tags_boxes', models.ManyToManyField(related_name='tag_boxes', to='images.TagBox')),
            ],
        ),
        migrations.CreateModel(
            name='TagPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=7)),
                ('x', models.FloatField(blank=True)),
                ('y', models.FloatField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='tagimage',
            name='tags_points',
            field=models.ManyToManyField(related_name='tags_points', to='images.TagPoint'),
        ),
        migrations.AddField(
            model_name='tagimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.Image'),
        ),
    ]
