# Generated by Django 2.2.1 on 2019-07-24 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('state', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=7)),
                ('primitive', models.CharField(choices=[('Box', 'Box'), ('Point', 'Point')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Dataset')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unique', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=1024)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                              to='images.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_by',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_by',
                                   to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Experiment')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tag',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_tags',
                                   to='images.ImageTag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type',
                                           to='images.AnnotationType')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTagBox',
            fields=[
                ('individualtag_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='images.IndividualTag')),
                ('x_top_left', models.FloatField(blank=True)),
                ('y_top_left', models.FloatField(blank=True)),
                ('width', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
            ],
            bases=('images.individualtag',),
        ),
        migrations.CreateModel(
            name='IndividualTagPoint',
            fields=[
                ('individualtag_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='images.IndividualTag')),
                ('x', models.FloatField(blank=True)),
                ('y', models.FloatField(blank=True)),
            ],
            bases=('images.individualtag',),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Experiment'),
        ),
    ]
