# Generated by Django 2.1.7 on 2019-04-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anotaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
                ('imagenes', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
                ('anotaciones', models.ManyToManyField(to='anotaciones.Anotacion')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imagenes.Dataset')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Equipo')),
            ],
        ),
    ]
