# Generated by Django 2.1.7 on 2019-04-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
