# Generated by Django 2.1.7 on 2019-04-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0002_auto_20190423_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
